defmodule KusaData.Watches.Notification do
  @moduledoc "A deduplicated in-app notification generated by a watch change."

  use Ecto.Schema

  import Ecto.Changeset

  alias KusaData.Accounts.User
  alias KusaData.Watches.Watch

  schema "notifications" do
    field(:type, :string)
    field(:payload, :map, default: %{})
    field(:read_at, :utc_datetime_usec)
    field(:delivered_at, :utc_datetime_usec)
    field(:dedup_key, :string)
    field(:delivery_status, :string, default: "pending")
    field(:delivery_attempts, :integer, default: 0)
    field(:last_error, :string)

    belongs_to(:user, User)
    belongs_to(:watch, Watch)

    timestamps(type: :utc_datetime_usec, inserted_at: :created_at, updated_at: false)
  end

  def changeset(notification, attrs) do
    notification
    |> cast(attrs, [
      :type,
      :payload,
      :read_at,
      :delivered_at,
      :dedup_key,
      :delivery_status,
      :delivery_attempts,
      :last_error,
      :user_id,
      :watch_id
    ])
    |> validate_required([:type, :user_id, :dedup_key])
    |> unique_constraint(:dedup_key)
  end
end
